protected/models/User.php
<?php

Yii::import('application.models._base.BaseUser');

class User extends BaseUser
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
        
        public function afterValidate() {
            $this->password=  md5($this->password);
        }
        
        public function dataROle($role) {
            $v="";
            if($role==0)
            {
                $v="Root";
            }
            if($role==1)
            {
                $v="Admin";
            }
            if($role==1)
            {
                $v="Anggota";
            }
            return $v;
        }
}

protected/controllers/UserController.php
<?php
/*
 * Dibuat oleh : Ade Hendini
 * adehendini@gmail.com
 */
class UserController extends GxController {

        public $judul="User";

public function filters() {
	return array(
			'accessControl', 
			'postOnly + delete',
			);
}

public function accessRules() {
        $root=array('index','delete','ubah','view');
        $arr=array('ubah','view');
        $semua=array('view','ubah');
	return array(
			array('allow', 
				'actions'=>$root,
				'expression'=>'Yii::app()->user->isRoot()',
				),
			array('allow', 
				'actions'=>$arr,
				'expression'=>'Yii::app()->user->isRoot() OR Yii::app()->user->isAdmin()',
				),
			array('allow', 
				'actions'=>$arr,
				'expression'=>'Yii::app()->user->isRoot() OR Yii::app()->user->isAdmin() OR Yii::app()->user->isAnggota()',
				),
			array('deny', 
				'users'=>array('*'),
				),
			);
}
        public function actionIndex() {
                $this->judul="Pengguna";
		$model = new User('search');
		$model->unsetAttributes();

		if (isset($_POST['string']))
			$model->setPencarian($_POST['string']);

		$this->render('index', array(
			'model' => $model,
		));
	}
        
        public function actionView() {
            $this->judul="Profil";
            $id=  Yii::app()->user->id;
            
            //ubah password
                $model = new UserPasswordForm;
                
                if(isset($_POST['ajax']) && $_POST['ajax']==='change_password-form')
                {
                    echo CActiveForm::validate($model);
                    Yii::app()->end();
                }

                if(isset($_POST['UserPasswordForm']))
                {
                    $model->attributes=$_POST['UserPasswordForm'];
                    if($model->validate() && $model->changePassword())
                    {
                        Dialog::message('Berhasil', 'Password Berhasil Diubah');
                        $this->redirect(array('profil/'));
                    }
                }
                
            //ubah gambar profil
                $user= User::model()->findByPk(Yii::app()->user->id);
                if(isset($_POST['User']))
                {
                    $user->setAttributes($_POST['User']);
                    $avatar=NULL;
                    if(strlen(trim(CUploadedFile::getInstance($user, 'avatar')))>0)
                    {
                        $avatar=  CUploadedFile::getInstance($user, 'avatar');
                        $ext_avatar = $avatar->extensionName;
                        $user->avatar="{$user->email}.{$ext_avatar}";
                     }
                     if ($user->save())
                     {
                        if(strlen(trim($avatar))>0)
                        {
                            $avatar->saveAs('img/'.$user->avatar);
                        }
                        Dialog::message('Berhasil', 'Avatar Berhasil Diubah');
			$this->redirect(array('profil/'));
                     }
                }
                
            $this->render('view', array(
                'model' => $this->loadModel($id, 'User'),
                'user'=>$model,
                'avatar'=>$user,
            ));
        }
        

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) 
                {
                    try{
			$this->loadModel($id, 'User')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('index'));
                    }catch(CDbException $e){
                        if($e->getCode()===23000)
                        {
                            throw new CHttpException(400, Yii::t('err', 'Data Ini Tidak Dapat Dihapus'));
                        }else{
                            throw $e;
                        }
                    }
		}else
                    throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}
        
        public function actionUbah() {
            if(Yii::app()->request->isAjaxRequest)
                {
                    Yii::import('bootstrap.components.TbEditableSaver');
                    $es=new TbEditableSaver('User');
                    $es->update();
                }
                else
                    throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
        }

}

protected/views/user/_change_password.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="box box-solid box-info">
    <div class="box-header">
        <h3 class="box-title">Ubah Password</h3>
    </div>
    <div class="box-body">
<?php $form = $this->beginWidget('booster.widgets.TbActiveForm', array(
    'id' => 'change_password-form',
    'enableAjaxValidation' => false,
    'type'=>'horizontal',
    //'htmlOptions'=>array('class'=>'well'),
));
?>
        <?php // echo $form->textFieldGroup($model,'username',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>30)))); ?>
        <?php echo $form->passwordFieldGroup($model,'currentPassword',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>100)))); ?>
        <?php echo $form->passwordFieldGroup($model,'newPassword',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>100)))); ?>
        <?php echo $form->passwordFieldGroup($model,'newPassword_repeat',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>100)))); ?>
        
<div class="form-actions">                
<?php $this->widget('booster.widgets.TbButton', array(
            'buttonType'=>'submit',
            'context'=>'primary',
            'label'=>'Simpan Perubahan',
        )); ?>
</div>    
<?php $this->endWidget(); ?>
    </div>
</div>
    

protected/views/user/_form.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<?php $form = $this->beginWidget('booster.widgets.TbActiveForm', array(
	'id' => 'user-form',
	'enableAjaxValidation' => false,
        'type'=>'horizontal',
));
?>
<?php echo $form->errorSummary($model); ?>

		<?php echo $form->textFieldGroup($model,'email',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>100)))); ?>
		<?php echo $form->textFieldGroup($model,'nama',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>50)))); ?>
		<?php echo $form->passwordFieldGroup($model,'password',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>100)))); ?>
		<?php echo $form->textFieldGroup($model,'avatar',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>100)))); ?>
		<?php echo $form->textFieldGroup($model, 'status'); ?>
		<?php echo $form->textFieldGroup($model, 'role'); ?>



<div class="form-actions">                
<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			//'context'=>'primary',
			'label'=>$model->isNewRecord ? 'Simpan' : 'Simpan Perubahan',
                        'icon'=>'fa fa-save fa-fw',
		)); ?>
    &nbsp;
<?php echo CHtml::link('<span class="glyphicon glyphicon-share-alt"></span> Kembali', array('index'), array('class'=>'btn btn-default')) ?>
</div>    
<?php $this->endWidget(); ?>

protected/views/user/_pencarian.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<?php echo CHtml::beginForm(CHtml::normalizeUrl(array('index')), 'post', array('class'=>'form-inline','style'=>'width:100%')) ?>
<?php echo CHtml::textField('string', (isset($_POST['string'])) ? $_POST['string'] : '', array('class'=>'form-control col-xs-4','placeholder'=>'Email/Nama')) ?>
<?php echo CHtml::tag('button',
                array('class' => 'btn btn-default','type'=>'submit'),
                '<i class="glyphicon glyphicon-search"></i> Cari'); ?>
<?php echo CHtml::endForm(); ?>

protected/views/user/create.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-6">
        <?php
                $this->renderPartial('_form', array(
                                'model' => $model,
                                'buttons' => 'create'));
                ?>
        <?php echo Yii::t('app', 'Kolom dengan tanda'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'harus diisi'); ?>.
    </div>
</div>

protected/views/user/index.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-12">
        <div class="pull-right">
            <?php $this->renderPartial('_pencarian'); ?>
        </div>
<?php $this->widget('booster.widgets.TbGridView', array(
	'id' => 'user-grid',
	'dataProvider' => $model->pencarian(),
	//'filter' => $model,
        'summaryText'=>'',
	'columns' => array(
//		'id',
		'email',
		'nama',
		array(
                    'class' => 'booster.widgets.TbEditableColumn',
                    'name'=>'status',
                    'editable' => array(
                        'type' => 'select',
                        //'value'=>'$data->status==1 ? "Aktif":"Non Aktif"',
                        'url' => $this->createUrl('user/ubah'),
                        'source' => array(1=>'Aktif',0=>'NonAktif'),
                )),
		array(
                    'class' => 'booster.widgets.TbEditableColumn',
                    'name'=>'role',
                    'editable' => array(
                        'type' => 'select',
                        //'value'=>'$data->status==1 ? "Aktif":"Non Aktif"',
                        'url' => $this->createUrl('user/ubah'),
                        'source' => array(1=>'Admin',2=>'Anggota'),
                )),
		array(
			'header' => 'Aksi',
                        //'htmlOptions'=>array('width'=>'80'),
			'class' => 'booster.widgets.TbButtonColumn',
                        'template'=>'{delete}',
		),
	),
)); ?>
    </div>
</div>

protected/views/user/update.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-6">
<?php echo CHtml::link('<span class="glyphicon glyphicon-share-alt"></span> Kembali', array('index'), array('class'=>'btn btn-default')) ?>
<br><br>
<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>
<?php echo Yii::t('app', 'Kolom dengan tanda'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'harus diisi'); ?>.
    </div>
</div>

protected/views/user/view.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<?php $baseurl=Yii::app()->baseUrl; ?>
<div class="row">
    <div class="col-lg-2">
        <?php echo CHtml::image($baseurl.'/img/'.$model->avatar, $model->nama,array('width'=>'100%')); ?>
        <?php $form = $this->beginWidget('booster.widgets.TbActiveForm', array(
            'id' => 'user-form',
            'enableAjaxValidation' => false,
            //'type'=>'horizontal',
            'htmlOptions'=>array('enctype'=>'multipart/form-data'),
        ));
        ?>
        <?php echo $form->fileField($avatar,'avatar'); ?>
        <?php echo $form->error($avatar,'avatar'); ?>
        <div class="form-actions">                
        <?php $this->widget('booster.widgets.TbButton', array(
                    'buttonType'=>'submit',
                    //'context'=>'primary',
                    'label'=>'Upload Avatar',
                    'icon'=>'glyphicon glyphicon-floppy-disk',
                )); ?>
        </div>    
        <?php $this->endWidget(); ?>
    </div>
    <div class="col-lg-10">
        <table class="table">
            <tr>
                <th>Email</th>
                <td><?php echo $model->email; ?></td>
            </tr>
            <tr>
                <th>Nama</th>
                <td><?php
                        $this->widget('booster.widgets.TbEditableField',
                            array(
                                'type' => 'text',
                                'model' => $model,
                                'attribute' => 'nama', // $model->name will be editable
                                'url' => $this->createUrl('user/ubah'), //url for submit data
                            )
                        );
                    ?>
                </td>
            </tr>
            <tr>
                <th>Status</th>
                <td><?php echo $model->status==1 ? "Aktif":"Non Aktif"; ?></td>
            </tr>
            <tr>
                <th>Role</th>
                <td><?php echo User::model()->dataRole($model->role);  ?></td>
            </tr>
        </table>
        
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <?php $this->renderPartial('_change_password',array('model'=>$user)); ?>
    </div>
</div>