protected/controllers/ForumController.php
<?php
/*
 * Dibuat oleh : Ade Hendini
 * adehendini@gmail.com
 */
class ForumController extends GxController {

        public $judul="Forum";

        public function filters() {
                return array(
                                'accessControl', 
                                'postOnly + delete',
                                );
        }

        public function accessRules() {
                $arr=array('index','create','thread','view','komentar','upload','uploadKomentar');
                
                return array(
                                array('allow', 
                                        'actions'=>$arr,
                                        'expression'=>'Yii::app()->user->isRoot() OR Yii::app()->user->isAdmin() OR Yii::app()->user->isAnggota()',
                                        ),
                                array('deny', 
                                        'users'=>array('*'),
                                        ),
                                );
        }
        
        public function actionIndex() {
		
		if (isset($_POST['string']))
                {
                    if(empty($_POST['string']))
                    {
                        $model = Kategori::model()->findAll();
                        $this->render('index', array(
                            'model' => $model,
                        ));
                    }else{
                        $string=$_POST['string'];
                        $criteria=new CDbCriteria();
                        $criteria->addSearchCondition( 'judul', $string, true, 'OR' );
                        $criteria->addSearchCondition( 'isi', $string, true, 'OR' );
                        $dataProvider = new CActiveDataProvider('Thread',array(
                            'criteria'=>$criteria,
                            'pagination'=>array(
                                    'pageSize'=>10,
                            ),
                            'sort'=>array(
                                'defaultOrder'=>'tanggal DESC',
                            )
                        ));
                        $this->render('cari', array(
                            'dataProvider' => $dataProvider,
                        ));
                    }
                }else{
                    $model = Kategori::model()->findAll();
                    $this->render('index', array(
			'model' => $model,
                    ));
                }
	}
        
        public function actionThread($id) {
                $kategori = Kategori::model()->findByPk($id);
                $this->small=$kategori->kategori;
                $criteria=new CDbCriteria();
                if(isset($_POST['string']))
                {
                    $string=$_POST['string'];
                    $criteria->addSearchCondition( 'judul', $string, true, 'OR' );
                    $criteria->addSearchCondition( 'isi', $string, true, 'OR' );
                    $criteria->addSearchCondition( 'kategori_id', $id, true, 'AND' );
                }else{
                    $criteria->addSearchCondition( 'kategori_id', $id, true, 'AND' );
                }
                
		$dataProvider = new CActiveDataProvider('Thread',array(
                    'criteria'=>$criteria,
                    'pagination'=>array(
                            'pageSize'=>10,
                    ),
                    'sort'=>array(
                        'defaultOrder'=>'tanggal DESC',
                    )
                ));
                $this->render('thread', array(
                    'dataProvider' => $dataProvider,
                    'kategori'=>$kategori,
                ));
        }
        
	public function actionCreate($id) {
		$model = new Thread;
                $kategori = Kategori::model()->findByPk($id);
                $this->small=$kategori->kategori;
                $model->kategori_id=$kategori->id;
                $model->user_id=  Yii::app()->user->id;
                $model->tanggal=date('Y-m-d h:i:s');
                
		if (isset($_POST['Thread'])) {
			$model->setAttributes($_POST['Thread']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
                                        Dialog::message('Berhasil', 'Thread Berhasil Disimpan');
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 
                    'model' => $model,
                    'kategori'=>$kategori,
                    ));
	}
        
        public function actionView($id) {
                $model =$this->loadModel($id, 'Thread');
                $this->small = $model->kategori;
                
                $criteria=new CDbCriteria();
                $criteria->addSearchCondition( 'thread_id', $model->id, true, 'AND' );
                $dataProvider = new CActiveDataProvider('Komentar',array(
                    'criteria'=>$criteria,
                    'pagination'=>array(
                            'pageSize'=>3,
                    ),
                    'sort'=>array(
                        'defaultOrder'=>'tanggal ASC',
                    )
                ));
                $pager=$dataProvider->pagination;
                $pager->itemCount=$dataProvider->totalItemCount;
                if(!Yii::app()->request->isAjaxRequest)
                        $pager->currentPage=$pager->pageCount;

                
                //komentari
                $komentar = new Komentar;
                $komentar->thread_id=$model->id;
                $komentar->tanggal=date('Y-m-d h:i:s');
                $komentar->user_id=  Yii::app()->user->id;

                if (isset($_POST['Komentar'])) {
                    $komentar->setAttributes($_POST['Komentar']);

                    if ($komentar->save()) {
                            if (Yii::app()->getRequest()->getIsAjaxRequest())
                                    Yii::app()->end();
                            else
                                Dialog::message('Berhasil', 'Thread Berhasil dikomentari');
                                $this->redirect(array('view','id'=>$model->id));
                            }
                }
                
		$this->render('view', array(
			'model' => $model,
                        'komentar'=>$komentar,
                        'dataProvider'=>$dataProvider,
		));
	}

	public function actionKomentar($id) {
            $thread = Thread::model()->findByPk($id);
            $model = new Komentar;
            $thread = Thread::model()->findByPk($id);
            $model->thread_id=$thread->id;
            $model->tanggal=date('Y-m-d h:i:s');
            $model->user_id=  Yii::app()->user->id;

            if (isset($_POST['Komentar'])) {
		$model->setAttributes($_POST['Komentar']);

		if ($model->save()) {
			if (Yii::app()->getRequest()->getIsAjaxRequest())
				Yii::app()->end();
			else
                            Dialog::message('Berhasil', 'Thread Berhasil dikomentari');
                            $this->redirect(array('forum/view','id'=>$thread->id));
			}
            }

            $this->render('form_komentar', array( 
                        'model' => $model,
                        'thread'=>$thread
                    ));
        }
        
        public function actionUpload()
        {
            if($_FILES) // check if file upload exist
            {
                $target_path = Yii::app()->basePath.'/../gambar/forum/';  // directory in your server
                $ext_name=explode('.',basename($_FILES['upload']['name']));  // get extension from file upload
                $rand1 = rand(11111, 99999);
                $rand2 = rand(1111111111, 9999999999);
                $rand3 = date('Y-m-d');
                $filename= $rand2.'-'.$rand1.'-'.$rand2.'-'.$rand3;
                $fname=$filename.$ext_name[1];  // set your file name, 
                $target_path = $target_path.$fname;  // save path and name file

                if(!file_exists("$target_path"))// if we have set target path
                {
                      $message='';  // message variable, use to show message after upload file
                      $url='';   // url variable, use to set url image in your editor
                      $lower_ext=strtolower($ext_name[1]);  // check extension, validate type file
                      if ($lower_ext!='jpg' && $lower_ext!='jpeg' && $lower_ext!='png' && $lower_ext!='gif')
                      {
                        // if type file not allow
                        $message = "The image must be in either JPG, JPEG, GIF or PNG format."; 
                      }
                    else
                    {
                        // upload file to server
                        move_uploaded_file($_FILES['upload']['tmp_name'], $target_path);
                        echo 'Success Upload File';
                        // url will save directory. Note it, url is different with target path
                        // url will use in your editor, it will direct access to the path
                        $baseurl=  Yii::app()->baseUrl;
                        $url=$baseurl.'/gambar/forum/'.$fname;
                    }
                    $funcNum = $_GET['CKEditorFuncNum'] ;
                    // after save data, run code to call ckeditor function
                    echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($funcNum, '$url', '$message');</script>";
                  }
                  else
                  {
                      echo 'Failed Upload File';    
                  }
            }
        }
        
        public function actionUploadKomentar()
        {
            if($_FILES) // check if file upload exist
            {
                $target_path = Yii::app()->basePath.'/../gambar/komentar/';  // directory in your server

protected/views/forum/_form.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<?php $form = $this->beginWidget('booster.widgets.TbActiveForm', array(
	'id' => 'thread-form',
	'enableAjaxValidation' => false,
        //'type'=>'horizontal',
        
));
?>
<?php echo $form->errorSummary($model); ?>

		<?php echo $form->textFieldGroup($model,'judul',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>200)))); ?>
		<?php    $isi=$this->widget(
                            'booster.widgets.TbCKEditor',
                            array(
                            'model'=>$model,    
                            'name' => 'isi',
                            'attribute'=>'isi', 
                            ),true);  
                        echo $form->customFieldGroup($isi, $model ,'isi');
                  ?>    

<div class="form-actions">                
<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			//'context'=>'primary',
			'label'=>$model->isNewRecord ? 'Simpan' : 'Simpan Perubahan',
                        'icon'=>'fa fa-save fa-fw',
		)); ?>
    &nbsp;
<?php echo CHtml::link('<span class="glyphicon glyphicon-share-alt"></span> Batal', array('index'), array('class'=>'btn btn-default')) ?>
</div>    
<?php $this->endWidget(); ?>

<script type="text/javascript">
    CKEDITOR.replace('Thread[isi]', {
                height: 300,
                //width : 100,
                // this code use for activate image upload in your view, and it will execute the url that you want
                // when run it
                filebrowserImageUploadUrl: '<?php echo Yii::app()->createUrl("forum/upload")?>',

                // set toolbar that you want to show
                toolbar : [
                    //{'name' : 'document' , 'items' : ['Source']},
                    ['Cut','Copy','Paste','PasteText', 'PasteFromWord','-','Undo','Redo','Image'],
                    {'name' : 'basicstyles','items' : ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
                    { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
                ]
            } );
</script>

protected/views/forum/_form_komentar.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<?php $form = $this->beginWidget('booster.widgets.TbActiveForm', array(
	'id' => 'komentar-form',
	'enableAjaxValidation' => false,
));
?>
<?php echo $form->errorSummary($model); ?>

		<?php    $isi=$this->widget(
                            'booster.widgets.TbCKEditor',
                            array(
                            'model'=>$model,    
                            'name' => 'isi',
                            'attribute'=>'isi',    
                            ),true);  
                        echo $form->customFieldGroup($isi, $model ,'isi');?>  
                
<div class="form-actions">                
<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'label'=>'Komentari',
		)); ?>
    &nbsp;
</div>    
<?php $this->endWidget(); ?>

<script type="text/javascript">
    CKEDITOR.replace('Komentar[isi]', {
                height: 300,
                //width : 100,
                // this code use for activate image upload in your view, and it will execute the url that you want
                // when run it
                filebrowserImageUploadUrl: '<?php echo Yii::app()->createUrl("forum/uploadKomentar")?>',

                // set toolbar that you want to show
                toolbar : [
                    //{'name' : 'document' , 'items' : ['Source']},
                    ['Cut','Copy','Paste','PasteText', 'PasteFromWord','-','Undo','Redo','Image'],
                    {'name' : 'basicstyles','items' : ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
                    { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ], items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
                ]
            } );
</script>

protected/views/forum/_komentar.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="panel panel-default">
  <div class="panel-body">
    <?php echo $data->isi; ?>
  </div>
    <div class="panel-footer">
        <div class="row"> 
            <div class="col-lg-12">
        <div class="pull-left">
            <strong>Komentator : <?php echo $data->user->nama ?></strong><br>
        </div>
        <div class="pull-right">
            <strong>Tanggal komentar &nbsp;&nbsp;: <?php echo Konversi::tanggal($data->tanggal,"d M Y") ?></strong>
        </div>
            </div>
        </div>
    </div>  
</div>

protected/views/forum/_pencarian.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<?php $form = $this->beginWidget('GxActiveForm', array(
	//'action' => Yii::app()->createUrl($this->route),
        //'type'=>'horizontal',
	'method' => 'post',
        'htmlOptions'=>array('class'=>'form-inline')
)); ?>
    <div class="row">
      <div class="col-xs-12">
        <div class="input-group input-group-lg">
            <?php echo CHtml::textField('string', (isset($_POST['string'])) ? $_POST['string'] : '', array('class'=>'form-control','placeholder'=>'Pencarian')) ?>
          <div class="input-group-btn">
            <?php echo CHtml::tag('button',
                array('class' => 'btn btn-default','type'=>'submit'),
                '<i class="glyphicon glyphicon-search"></i> Cari'); ?>
          </div><!-- /btn-group -->
        </div><!-- /input-group -->
      </div><!-- /.col-xs-12 -->
    </div><!-- /.row -->
<?php $this->endWidget(); ?>

protected/views/forum/_thread.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"><?php echo CHtml::link($data->judul, array('view', 'id' => $data->id)); ?></h2>
  </div>
  <div class="panel-body">
    <?php echo substr(strip_tags($data->isi),0,250); ?>
    <?php echo CHtml::link('Selengkapnya...', array('view', 'id' => $data->id)); ?>  
  </div>
    <div class="panel-footer">
        <div class="row"> 
            <div class="col-lg-12">
        <div class="pull-left">
            <strong>Kategori &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <?php echo $data->kategori ?></strong><br>
            <strong>Jumlah Komentar &nbsp;: <?php echo Komentar::model()->jmlKomentar($data->id) ?></strong>
        </div>
        <div class="pull-right">
            <strong>Tanggal Post &nbsp;&nbsp;: <?php echo Konversi::tanggal($data->tanggal,"d M Y") ?></strong>
        </div>
            </div>
        </div>
    </div>  
</div>

protected/views/forum/cari.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-12">
      <?php $this->renderPartial('_pencarian'); ?>  
                
<?php $this->widget('booster.widgets.TbListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_thread',
)); ?>
    </div>
</div>

protected/views/forum/create.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-12">
        <?php
                $this->renderPartial('_form', array(
                                'model' => $model,
                                'buttons' => 'create'));
                ?>        <?php echo Yii::t('app', 'Kolom dengan tanda'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'harus diisi'); ?>.
    </div>
</div>

protected/views/forum/index.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-12">
        <?php $this->renderPartial('_pencarian'); ?>
        <br>
        <?php foreach ($model as $baris) : ?>
        <?php $jmlForum = Kategori::model()->forum($baris->id); ?>
        <?php $tglAkhir = Thread::model()->latestPost($baris->id);
            if(empty($tglAkhir))
            {
                $tglAkhir="00-00-0000";
            }else{
                $tglAkhir = Konversi::tanggal($tglAkhir,"d M Y");
            }           
        ?>
        <?php echo CHtml::link("
        <div class='well well-sm'>
            $baris->kategori ($jmlForum)
            <div class='pull-right'>
                Post Terakhir : $tglAkhir
            </div>    
        </div>
        ",array('thread','id'=>$baris->id)); ?>
        <?php endforeach; ?>
    </div>
</div>

protected/views/forum/thread.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-12">
      <?php $this->renderPartial('_pencarian'); ?>  
        <br>
<?php echo CHtml::link('<span class="glyphicon glyphicon-share-alt"></span> Kategori Forum', array('index'), array('class'=>'btn btn-default')) ?>
        &nbsp;
<?php echo CHtml::link('<span class="glyphicon glyphicon-question-sign"></span> Tanya', array('create','id'=>$kategori->id), array('class'=>'btn btn-default')) ?>
        
                
<?php $this->widget('booster.widgets.TbListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_thread',
)); ?>
    </div>
</div>

protected/views/forum/view.php
<?php
/*
 * Oleh : Ade Hendini
 * adehendini@gmail.com
 */
?>
<div class="row">
    <div class="col-lg-12">
<?php echo CHtml::link('<span class="glyphicon glyphicon-share-alt"></span> Kategori Forum', array('index'), array('class'=>'btn btn-default')) ?>
        
        <h3><?php echo $model->judul; ?></h3>
        <hr>
        <?php echo $model->isi ?>
        <hr>
<strong>Di Post Oleh &nbsp;&nbsp;&nbsp;: <?php echo $model->user->nama ?></strong><br>
<strong>Tanggal post &nbsp;&nbsp;: <?php echo Konversi::tanggal($model->tanggal,"d M Y") ?></strong>
<hr>

<h4>Komentar</h4>
<?php $this->widget('booster.widgets.TbListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_komentar',
)); ?>
<?php
$this->renderPartial('_form_komentar', array('model'=>$komentar));
?>
    </div>
</div>